version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - .docker/config/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php

  php:
    build: .docker/php
    container_name: sf_php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: sf_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: